apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-dbm-accounting
  namespace: dbm-accounting
  labels:
    name: dbm-accounting
  annotations:
    nginx.ingress.kubernetes.io/client-max-body-size: 100m
    nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 100m
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "6000s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "6000s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "6000s"

spec:
  ingressClassName: nginx

  rules:
    - host: dev-accounting.digitalberkahmandiri.com
      http:
        paths:
          - pathType: Prefix
            path: "/api"
            backend:
              service:
                name: svc-dbm-accounting
                port:
                  number: 8080

          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: svc-dbm-accounting-fe
                port:
                  number: 3000
   

    
